
image: mcr.microsoft.com/playwright:focal

stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: "$CI_PROJECT_ID-maven"
  paths:
    - .m2/repository

e2e_tests:
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y apt-transport-https curl software-properties-common
    # Install Java + Maven
    - apt-get install -y openjdk-17-jdk maven
    # Microsoft Edge repo
    - curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/ms.gpg
    - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/ms.gpg] https://packages.microsoft.com/repos/edge stable main" > /etc/apt/sources.list.d/microsoft-edge.list
    - apt-get update
    - apt-get install -y microsoft-edge-stable libnss3 libgbm1 libasound2 fonts-liberation
  script:
    - pwd
    - java -version
    - mvn -version
    - mvn clean test
#    - ls -R target
    # Send Cucumber Report Email
#    - |
#      echo "cucumer" | \
#      mail -s "Cucumber Automation Test Report" \
#      -a target/cucumber-reports.html \
#      "${EMAIL_TO}"
#  artifacts:
#      when: always
#      paths:
#        - target/cucumber-reports.html
#      expire_in: 1 week
#    - mvn -B -U clean test -Dbrowser="$BROWSER" -Dcucumber.plugin=pretty -Dcucumber.monochrome=true
#  artifacts:
#    when: always
#    paths:
#      - target/cucumber-reports/
#      - target/site/
#  script:
#    - echo "BDD run finished. Pages link: $CI_PAGES_URL" | mail -s "BDD Execution Report" poojasnair21@gmail.com
#pages:
#  stage: report
#  script:
#    - mkdir -p public
#    - cp -r target/cucumber-reports/* public/ || echo "No cucumber reports"
#    - cp -r target/site/* public/ || echo "No site reports"
#  artifacts:
#    paths:
#      - public
#  rules:
#    - if: $CI_JOB_STATUS == "success"