browser=edge
headless=false
url=https://www.saucedemo.com/
username=standard_user
password=secret_sauce
reportConfigPath=C:\Users\grace\IdeaProjects\MainProject_CucumberBDD\extent-config.xml
reports=target/cucumber-report.html